/**
 * 项目名称列表配置
 * 包含中英文项目名称
 */

// 项目名称列表 - 包含英文原名和中文翻译
export const projectNamesList = [
  { name: "vPaste", zhName: "剪切板工具" },
  { name: "Sheas Cealer", zhName: "SNI伪造工具" },
  { name: "Best Directories", zhName: "导航工具" },
  { name: "TalkingAvatar", zhName: "AI视频生成" },
  { name: "AI 塔罗耳语", zhName: "AI塔罗占卜" },
  { name: "AI 雷诺曼占卜", zhName: "AI占卜工具" },
  { name: "SparkleEasy", zhName: "开发效率工具" },
  { name: "Recap", zhName: "内容摘要工具" },
  { name: "AI Best Tools", zhName: "AI工具导航" },
  { name: "FileNeatAI", zhName: "文件整理工具" },
  { name: "Temp Mail", zhName: "临时邮箱" },
  { name: "AI Detector", zhName: "AI内容检测" },
  { name: "X-Comfort-Browser", zhName: "浏览器插件" },
  { name: "jarkViewer", zhName: "看图工具" },
  { name: "FtpServer", zhName: "FTP服务" },
  { name: "小天气", zhName: "天气小部件" },
  { name: "Img2Video", zhName: "视频生成" },
  { name: "Bluesky Video Downloader", zhName: "视频下载器" },
  { name: "Yes/No 塔罗 AI", zhName: "塔罗AI" },
  { name: "ProjectHunt", zhName: "项目分享平台" },
  { name: "CheapGpt", zhName: "AI接口平台" },
  { name: "如快", zhName: "启动器工具" },
  { name: "aiseka.com", zhName: "色彩管理工具" },
  { name: "liusha tech detector", zhName: "技术分析工具" },
  { name: "MIB", zhName: "数据备份" },
  { name: "Subrise", zhName: "Reddit运营工具" },
  { name: "Hurricane Simulator", zhName: "飓风模拟器" },
  { name: "Image to excel", zhName: "图片转表格" },
  { name: "Sprunked", zhName: "音乐游戏" },
  { name: "Notion Exporter", zhName: "Notion内容分享" },
  { name: "扇贝单词助手V3", zhName: "英语学习助手" },
  { name: "Inpodcast AI", zhName: "文档转音频" },
  { name: "MvpFast", zhName: "MVP开发模板" },
  { name: "iFinder", zhName: "网页插件" },
  { name: "图片分割器", zhName: "图片分割工具" },
  { name: "Abgerny", zhName: "模组创作平台" },
  { name: "Biofy", zhName: "个人主页创建" },
  { name: "Hawthorn Game", zhName: "沙盒游戏" },
  { name: "AI 形象照", zhName: "AI形象生成" },
  { name: "Notion Exporter", zhName: "Notion导出工具" },
  { name: "扇贝单词助手V3", zhName: "语言学习助手" },
  { name: "Inpodcast AI", zhName: "播客生成工具" },
  { name: "MvpFast", zhName: "MVP构建模板" },
  { name: "iFinder", zhName: "关键词高亮" },
  { name: "图片分割器", zhName: "图片分割器" },
  { name: "Abgerny", zhName: "游戏模组" },
  { name: "Fast Food Simulator", zhName: "模拟经营游戏" },
  { name: "Biofy", zhName: "个人主页工具" },
  { name: "Hawthorn Game", zhName: "沙盒游戏" },
  { name: "AI 形象照", zhName: "AI形象照生成" },
  { name: "投资策略模拟器", zhName: "投资策略模拟器" },
  { name: "Image Splitter", zhName: "图像分割工具" },
  { name: "小而美工具", zhName: "生活工具小程序" },
  { name: "Poster Generator", zhName: "海报生成器" },
  { name: "mediago", zhName: "视频下载工具" },
  { name: "EzyGraph", zhName: "图表生成工具" },
  { name: "微信助手 Pro", zhName: "微信助手" },
  { name: "海投简历", zhName: "简历投递工具" },
  { name: "Colorbox Mustard", zhName: "音乐创作平台" },
  { name: "Web AI助手", zhName: "Web AI助手" },
  { name: "Sprunki Incredibox", zhName: "音乐创作游戏" },
  { name: "QRCode.fun", zhName: "二维码生成工具" },
  { name: "高亮“广告”", zhName: "广告高亮扩展" },
  { name: "IP.IM", zhName: "IP查询工具" },
  { name: "开源许可证选择器", zhName: "许可证选择器" },
  { name: "SoColoring", zhName: "填色生成" },
  { name: "OkeiAI", zhName: "AI导航站" },
  { name: "TikTok Voice Generator", zhName: "TTS工具" },
  { name: "SeeWhatNewAI", zhName: "AI产品目录" },
  { name: "Random Pokemon Generator", zhName: "宝可梦生成器" },
  { name: "Tabbiy", zhName: "标签管理" },
  { name: "JSON For You", zhName: "JSON处理工具" },
  { name: "Compress JPG", zhName: "图片压缩工具" },
  { name: "SenGen", zhName: "句子生成器" },
  { name: "MiKaPo", zhName: "动捕工具" },
  { name: "OC Maker", zhName: "角色图像生成" },
  { name: "退休计算器", zhName: "退休计算器" },
  { name: "退休年龄计算器", zhName: "退休年龄计算" },
  { name: "Show HN Today", zhName: "HackerNews热门" },
  { name: "NewPet", zhName: "桌面宠物" },
  { name: "CloudOTP", zhName: "验证工具" },
  { name: "Flux AI", zhName: "图片生成" },
  { name: "AI Lyrics Generator", zhName: "歌词生成" },
  { name: "放大镜录屏", zhName: "录屏插件" },
  { name: "IT 摇篮曲", zhName: "IT知识平台" },
  { name: "美丽记账", zhName: "记账工具" },
  { name: "Flux AI Image Generator", zhName: "AI图像生成" },
  { name: "ToolList AI", zhName: "AI工具搜索" },
  { name: "番石榴实验室", zhName: "OCR识别" },
  { name: "Hotel Corporate Codes", zhName: "酒店协议代码" },
  { name: "sitemap 生成器", zhName: "网站地图" },
  { name: "Kite 待办", zhName: "待办应用" },
  { name: "Emoji Spark", zhName: "Emoji搜索" },
  { name: "AI Anime Generator", zhName: "AI动漫生成" },
  { name: "Text Compare & Merge", zhName: "文本对比工具" },
  { name: "SVG to ICO", zhName: "图标转换" },
  { name: "流沙 SEO", zhName: "SEO知识分享" },
  { name: "撩妹神器", zhName: "AI辅助工具" },
  { name: "奇异字体生成器", zhName: "字体生成器" },
  { name: "下一本读什么", zhName: "书单推荐" },
  { name: "Awesome Flux AI", zhName: "AI资料导航" },
  { name: "Perchance AI", zhName: "图片生成平台" },
  { name: "TikTok 收益计算器", zhName: "收益计算器" },
  { name: "微芒计划", zhName: "待办管理" },
  { name: "LLM GPU Helper", zhName: "GPU资源平台" },
  { name: "配图扫描", zhName: "配图识别" },
  { name: "AI Tool Trek", zhName: "AI工具导航" },
  { name: "Logo.surf", zhName: "图标生成" },
  { name: "AITDK SEO Extension", zhName: "SEO插件" },
  { name: "Comment Fast", zhName: "快速评论工具" },
  { name: "MP4 to MP3", zhName: "格式转换" },
  { name: "SpeakGo", zhName: "同传工具" },
  { name: "IP.network", zhName: "IP查询" },
  { name: "DNS.fish", zhName: "DNS查询" },
  { name: "Midjourney Sref code 精选库", zhName: "风格固定库" },
  { name: "CosmeticCheck", zhName: "化妆品查询" },
  { name: "GPS测速仪", zhName: "GPS工具" },
  { name: "Query.Domains", zhName: "域名查询" },
  { name: "Favicon.im", zhName: "图标获取" },
  { name: "Geilio Timer", zhName: "计时器" },
  { name: "WR.DO", zhName: "DNS系统" },
  { name: "小篆传包", zhName: "安卓发布工具" },
  { name: "SVG to PNG", zhName: "图像转换" },
  { name: "Mejorar Imagen", zhName: "图像增强" },
  { name: "PackPack", zhName: "书签管理" },
  { name: "Animate Old Photos", zhName: "照片动画" },
  { name: "MyTracks", zhName: "轨迹记录" },
  { name: "Network Sniffer", zhName: "抓包工具" },
  { name: "Notion Mate", zhName: "Notion插件" },
  { name: "诶嘿(EI)", zhName: "加密聊天" },
  { name: "电商优惠券查找脚本", zhName: "优惠券查找" },
  { name: "Airtable iOS Shortcuts", zhName: "Airtable工具" },
  { name: "共鸣 Chat", zhName: "GPT聊天工具" },
  { name: "OncePower", zhName: "批量重命名工具" },
  { name: "值得一读技术博客", zhName: "技术博客" },
  { name: "X Detector", zhName: "AI内容检测" },
  { name: "RIZZ AI", zhName: "AI约会助手" },
  { name: "壁纸千寻", zhName: "壁纸工具" },
  { name: "小报童专栏导航", zhName: "导航工具" },
  { name: "韶光日记", zhName: "时间轴日记" },
  { name: "EcoPaste", zhName: "剪切板管理" },
  { name: "FurryAI", zhName: "艺术创作平台" },
  { name: "即时热点", zhName: "热点聚合站" },
  { name: "AI WITH.ME", zhName: "AI导航站" },
  { name: "AI Filter", zhName: "AI滤镜" },
  { name: "内容农场", zhName: "内容创作平台" },
  { name: "Midjourney 样式代码库", zhName: "样式代码库" },
  { name: "mpmd", zhName: "微信文章编辑器" },
  { name: "CraftRecord", zhName: "录制软件" },
  { name: "微软 TTS 下载器", zhName: "TTS下载器" },
  { name: "亲戚称呼计算器", zhName: "称呼计算器" },
  { name: "Siphon 吸词", zhName: "生词翻译工具" },
  { name: "AITOOLIST", zhName: "AI信息平台" },
  { name: "m3u8下载器", zhName: "视频下载器" },
  { name: "PixarAI", zhName: "AI图像生成" },
  { name: "billd-live", zhName: "直播平台" },
  { name: "billd-desk", zhName: "远程桌面" },
  { name: "Case Convert Online", zhName: "大小写转换" },
  { name: "AigoTools", zhName: "导航工具" },
  { name: "Dubbo-Desktop-Manager", zhName: "Dubbo管理软件" },
  { name: "去水印下载", zhName: "去水印工具" },
  { name: "MermaidHelp", zhName: "流程图工具" },
  { name: "Trace", zhName: "数据分析工具" },
  { name: "aifly.tools", zhName: "AI工具站" },
  { name: "快图", zhName: "批量图片生成" },
  { name: "html2image", zhName: "HTML转图像" },
  { name: "jpgHi", zhName: "图片处理" },
  { name: "IDjpg", zhName: "图片风格化" },
  { name: "全王探测", zhName: "直播源搜索" },
  { name: "原色", zhName: "颜色查询" },
  { name: "微信助手", zhName: "微信助手" },
  { name: "微芒计划", zhName: "待办管理" },
  { name: "封面图", zhName: "封面图制作" },
  { name: "好说", zhName: "语言陪练" },
  { name: "便签喵", zhName: "便签小工具" },
  { name: "倒数鸭", zhName: "倒数日小组件" },
  { name: "千盒工具", zhName: "在线工具大全" },
  { name: "AIMangaTranslator", zhName: "漫画翻译" },
  { name: "Dataflare", zhName: "数据库管理" },
  { name: "Bunpou", zhName: "日语学习工具" },
  { name: "Kana playground", zhName: "假名练习工具" },
  { name: "sg-exam", zhName: "教学管理" },
  { name: "OMP", zhName: "媒体播放器" },
  { name: "厨房定时器", zhName: "定时器" },
  { name: "APK DOWNLOAD", zhName: "APK下载站" },
  { name: "91化简", zhName: "简历设计工具" },
  { name: "项目列表", zhName: "项目列表" },
  { name: "中国色", zhName: "颜色工具" },
  { name: "Rap Generator", zhName: "说唱生成" },
  { name: "Brick Center", zhName: "乐高生成器" },
  { name: "梦幻工坊", zhName: "AI绘画" },
  { name: "ImageTools", zhName: "图片处理" },
  { name: "微寻", zhName: "扫码登录" },
  { name: "英语汪", zhName: "英语学习" },
  { name: "言叶", zhName: "笔记软件" },
  { name: "Any Secret", zhName: "密码管理" },
  { name: "iMessage AI 助手", zhName: "iMessage AI" },
  { name: "tieba-toolbox", zhName: "贴吧工具箱" },
  { name: "IP Address Lookup", zhName: "IP查询" },
  { name: "微思文稿", zhName: "数据可视化" },
  { name: "AI Image Description Generator", zhName: "图片描述" },
  { name: "几枝", zhName: "诗词应用" },
  { name: "typing-word", zhName: "背单词工具" },
  { name: "SubRenamer", zhName: "字幕重命名" },
  { name: "FunClip", zhName: "视频剪辑" },
  { name: "兔兔答题", zhName: "在线考试" },
  { name: "OVO Tab", zhName: "标签页管理" },
  { name: "图生代码", zhName: "页面生成" },
  { name: "STranslate", zhName: "翻译工具" },
  { name: "实时金价", zhName: "黄金查询" },
  { name: "Honey Tab", zhName: "标签管理" },
  { name: "OCR 插件", zhName: "OCR插件" },
  { name: "shion", zhName: "时间追踪" },
  { name: "ElemSnap", zhName: "捕获工具" },
  { name: "AI Image Generator", zhName: "图像生成工具" },
  { name: "AI Video Generator", zhName: "视频生成工具" },
  { name: "自记账app", zhName: "记账应用" },
  { name: "自开票app", zhName: "开票应用" },
  { name: "RunFlow", zhName: "效率工具" },
  { name: "kimi小助手", zhName: "浏览器助手" },
  { name: "创想家 视频拍摄管理", zhName: "视频管理" },
  { name: "节点导航站", zhName: "导航站" },
  { name: "节点链接", zhName: "短链接生成" },
  { name: "新百词斩助手", zhName: "词汇助手" },
  { name: "smind.app", zhName: "思维脑图" },
  { name: "fly63 工具箱", zhName: "工具箱" },
  { name: "haiwai", zhName: "资源搜索" },
  { name: "sunost", zhName: "背景音乐" },
  { name: "toolss.ai", zhName: "AI工具导航" },
  { name: "ViBoard", zhName: "数据可视化" },
  { name: "海棠诗社", zhName: "诗词学习" },
  { name: "独立开发者导航站", zhName: "开发者导航" },
  { name: "DS Cloud", zhName: "NAS应用" },
  { name: "AI Undetect", zhName: "AI写作" },
  { name: "AI Humanizer", zhName: "AI改写工具" },
  { name: "简单设计", zhName: "设计工具" },
  { name: "Minitrade", zhName: "量化交易" },
  { name: "Markdown转图片", zhName: "Markdown转图片" },
  { name: "成绩分析", zhName: "成绩分析" },
  { name: "MyIP", zhName: "IP工具箱" },
  { name: "OhEarningsCal", zhName: "美股日历" },
  { name: "Macify", zhName: "屏保工具" },
  { name: "躺平计算器", zhName: "退休计算" },
  { name: "万物皆可DIY", zhName: "DIY应用" },
  { name: "SaaStores", zhName: "SaaS导航" },
  { name: "BindBook", zhName: "社交工具" },
  { name: "TTW", zhName: "旅行相册" },
  { name: "阿Q连线器", zhName: "围棋连线" },
  { name: "阿Q对弈宝", zhName: "围棋记谱" },
  { name: "阿Q棋钟", zhName: "围棋棋钟" },
  { name: "芙芙工具箱", zhName: "实用工具箱" },
  { name: "Photor", zhName: "截图美化" },
  { name: "fabritor", zhName: "图片编辑" },
  { name: "White80 Football", zhName: "AI教练" },
  { name: "InterviewAI", zhName: "面试工具" },
  { name: "记一杯", zhName: "饮品记录" },
  { name: "Youtube Dubbing", zhName: "视频语言转换" },
  { name: "SAFC", zhName: "导师评价平台" },
  { name: "自定义消息提示插件", zhName: "GitHub通知" },
  { name: "书签同步 Notion", zhName: "书签同步" },
  { name: "Meebox", zhName: "加密存储" },
  { name: "极简壁纸", zhName: "壁纸下载" },
  { name: "极简插件", zhName: "浏览器插件" },
  { name: "vmail", zhName: "临时邮箱" },
  { name: "Remove Bg", zhName: "AI图像工具" },
  { name: "Restore Photos", zhName: "AI图像修复" },
  { name: "Content Credentials", zhName: "内容验证" },
  { name: "Sora Build", zhName: "视频搜索" },
  { name: "AI时间线", zhName: "AI事件产出" },
  { name: "AI好物", zhName: "推荐工具" },
  { name: "简单记", zhName: "日记工具" },
  { name: "人格九道", zhName: "自我探索" },
  { name: "小狗听听", zhName: "播客应用" },
  { name: "Welibrary", zhName: "图书馆联动" },
  { name: "犬岛", zhName: "交友平台" },
  { name: "音流", zhName: "音乐播放器" },
  { name: "CodeCV", zhName: "简历工具" },
  { name: "C-Shopping", zhName: "电商系统" },
  { name: "PosterDesign", zhName: "海报设计" },
  { name: "小旅星", zhName: "旅行规划" },
  { name: "CapsWriter", zhName: "语音输入" },
  { name: "Toolkit", zhName: "工具集" },
  { name: "yft设计", zhName: "设计工具" },
  { name: "aspoem", zhName: "诗词学习" },
  { name: "奇趣网站", zhName: "网站导航" },
  { name: "创意导航", zhName: "创意导航" },
  { name: "AI语音记账", zhName: "AI记账" },
  { name: "xldream", zhName: "图片素材" },
  { name: "webhub123", zhName: "收藏管理" },
  { name: "PhotoFun", zhName: "图片编辑" },
  { name: "Markdown Sticky Note", zhName: "Markdown便签" },
  { name: "SEC.CAFE", zhName: "漏洞情报" },
  { name: "AI工具箱", zhName: "AI工具导航" },
  { name: "潮汐表表", zhName: "潮汐查询" },
  { name: "ChatAir", zhName: "Chat客户端" },
  { name: "我不会说出去", zhName: "心理咨询" },
  { name: "简约简历", zhName: "简历生成" },
  { name: "RepicApp", zhName: "图片压缩" },
  { name: "Photo Mint", zhName: "图片压缩" },
  { name: "拼拼古诗", zhName: "诗词游戏" },
  { name: "FluentRead", zhName: "翻译插件" },
  { name: "PPResume", zhName: "简历制作" },
  { name: "CoSS", zhName: "文件聚合" },
  { name: "FreeMind", zhName: "音乐氛围" },
  { name: "Tiny RDM", zhName: "Redis客户端" },
  { name: "17fei.fun", zhName: "互动游戏" },
  { name: "iconce", zhName: "SVG图标生成器" },
  { name: "DE好图壁纸", zhName: "图片分享" },
  { name: "Paint Board", zhName: "创意画板" },
  { name: "EarlyBird", zhName: "落地页构建" },
  { name: "Jing Bio", zhName: "个人品牌页面" },
  { name: "HeyForm", zhName: "表单工具" },
  { name: "TinySnap", zhName: "截图美化" },
  { name: "在线甘特图工具", zhName: "甘特图工具" },
  { name: "易匹配", zhName: "数据匹配" },
  { name: "h5-dooring", zhName: "页面制作" },
  { name: "Rare计划", zhName: "智能手表工具" },
  { name: "流畅阅读", zhName: "翻译插件" },
  { name: "人声和背景音乐分离工具", zhName: "音乐分离" },
  { name: "CV 声音克隆工具", zhName: "声音克隆" },
  { name: "Tabs Fast Easy", zhName: "浏览插件" },
  { name: "变量命名", zhName: "变量命名" },
  { name: "免费API共享平台", zhName: "API共享平台" },
  { name: "什么值得看", zhName: "资讯网站" },
  { name: "数数游戏", zhName: "数数游戏" },
  { name: "云剪切板", zhName: "云剪切板" },
  { name: "Github 图床", zhName: "图床工具" },
  { name: "自动捡漏机器人", zhName: "Steam工具" },
  { name: "免税地址生成器", zhName: "地址生成" },
  { name: "音乐歌单迁移助手", zhName: "歌单迁移" },
  { name: "JSONT", zhName: "JSON格式化" },
  { name: "Enconvo", zhName: "AI Launcher" },
  { name: "精准词获取工具", zhName: "词挖掘工具" },
  { name: "StockAI.Trade", zhName: "AI选股工具" },
  { name: "VOME", zhName: "语音备忘" },
  { name: "Podwise", zhName: "播客管理" },
  { name: "Inke笔记", zhName: "Web笔记" },
  { name: "ChatPPT", zhName: "PowerPoint生成" },
  { name: "百词斩助手", zhName: "百词斩助手" },
  { name: "虾答", zhName: "智能代理" },
  { name: "偷懒爱好者周刊", zhName: "周刊" },
  { name: "文丑", zhName: "AI助手平台" },
  { name: "AI导航", zhName: "AI导航" },
  { name: "表情小程序源码", zhName: "表情小程序" },
  { name: "OHTTPS", zhName: "HTTPS证书服务" },
  { name: "极简换算", zhName: "单位换算工具" },
  { name: "京墨", zhName: "诗词阅读" },
  { name: "MyServers", zhName: "服务器监控" },
  { name: "Teamlinker", zhName: "协作平台" },
  { name: "未道帮", zhName: "AI能力聚合" },
  { name: "AIGC工具导航", zhName: "AI工具导航" },
  { name: "AI抠图", zhName: "图片处理" },
  { name: "简约木鱼 iOS", zhName: "敲木鱼工具" },
  { name: "QQ 空间相册导出", zhName: "相册导出" },
  { name: "iChat", zhName: "AI助手" },
  { name: "tetris", zhName: "游戏" },
  { name: "MyNotes Keeper", zhName: "笔记工具" },
  { name: "情侣100件事", zhName: "情侣工具" },
  { name: "DeskWidgets", zhName: "桌面组件库" },
  { name: "AI画图王", zhName: "AI绘图" },
  { name: "加一", zhName: "习惯养成" },
  { name: "Island Widgets", zhName: "iOS工具" },
  { name: "Hamibot遥控器", zhName: "自动化工具" },
  { name: "火浣", zhName: "微信群爬虫" },
  { name: "AICodeConvert", zhName: "代码转换" },
  { name: "Genshin-GPT", zhName: "原神对话" },
  { name: "不懂药问", zhName: "用药查询" },
  { name: "极速图片压缩器", zhName: "图片压缩" },
  { name: "DevOpsGPT", zhName: "DevOps工具" },
  { name: "SimpleList", zhName: "文件管理" },
  { name: "SigniFi", zhName: "塔罗占卜" },
  { name: "单词之风", zhName: "背单词" },
  { name: "机画师", zhName: "AI绘图" },
  { name: "Nigate", zhName: "文件系统" },
  { name: "KHistory", zhName: "按键检测" },
  { name: "妙言", zhName: "Markdown笔记" },
  { name: "DenoPark", zhName: "RPG游戏" },
  { name: "Foresee", zhName: "预测跟踪" },
  { name: "雨巷", zhName: "白噪音工具" },
  { name: "MoodUp", zhName: "心情记录" },
  { name: "visualization-collection", zhName: "前端视觉" },
  { name: "ChatBoost", zhName: "ChatGPT客户端" },
  { name: "数字华容道", zhName: "数字拼图" },
  { name: "点点", zhName: "休闲游戏" },
  { name: "QuickNotes", zhName: "快记" },
  { name: "TaskMaster", zhName: "任务管家" },
  { name: "SoloBlog", zhName: "独立博客" },
  { name: "CodeSnippet", zhName: "代码片段" },
  { name: "MarkdownX", zhName: "马克记" },
  { name: "MiniGallery", zhName: "小画廊" },
  { name: "PhotoSnap", zhName: "拍照亭" },
  { name: "BudgetBuddy", zhName: "预算助手" },
  { name: "TinyTodo", zhName: "小待办" },
  { name: "DevHelper", zhName: "开发小助手" },
  { name: "FileDrop", zhName: "文件传输" },
  { name: "LightTerminal", zhName: "轻终端" },
  { name: "ClipBoarder", zhName: "剪贴工具" },
  { name: "RSSReader", zhName: "简易订阅" },
  { name: "MiniPlayer", zhName: "小播放器" },
  { name: "Weatherly", zhName: "天气向导" },
  { name: "QuickCalc", zhName: "快速计算器" },
  { name: "ScreenSnap", zhName: "截图工具" },
  { name: "CloudSync", zhName: "云端同步" },
  { name: "NoteBoard", zhName: "便签板" },
  { name: "PixelDraw", zhName: "像素绘图" },
  { name: "HabitTrack", zhName: "习惯追踪" },
  { name: "CodeRunner", zhName: "代码运行器" },
  { name: "IntuitionAI", zhName: "灵感助手" },
  { name: "Memos", zhName: "备忘录" },
  { name: "DrawDB", zhName: "绘图数据库" },
  { name: "MyTV", zhName: "我的电视" },
  { name: "Seal", zhName: "印章" },
  { name: "SensitiveWord", zhName: "敏感词过滤" },
  { name: "Motrix", zhName: "下载管理器" },
  { name: "SoybeanAdmin", zhName: "豆荚管理系统" },
  { name: "RemindersMenuBar", zhName: "菜单栏提醒" },
  { name: "Zealot", zhName: "热心者" },
  { name: "GmeekBlog", zhName: "极客博客" },
  { name: "DevHub", zhName: "开发者中心" },
  { name: "CloudflareSaaSStack", zhName: "云端SaaS套件" },
  { name: "Pearcleaner", zhName: "梨子清理器" },
  { name: "Fideo", zhName: "视频编辑器" },
  { name: "vCard", zhName: "电子名片" },
  { name: "Pintree", zhName: "图钉树" },
  { name: "RaySo", zhName: "代码美化" },
  { name: "PDFGuru", zhName: "PDF大师" },
  { name: "Revezone", zhName: "笔记区域" },
  { name: "MediaGo", zhName: "媒体播放器" },
  { name: "Flow", zhName: "工作流" },
  { name: "AutoSSL", zhName: "自动SSL证书" },
  { name: "WechatExporter", zhName: "微信导出工具" },
  { name: "LocalSend", zhName: "本地传输" },
  { name: "SiYuan", zhName: "思源笔记" },
  { name: "1Panel", zhName: "一面板" },
  { name: "DockerOSX", zhName: "Docker苹果系统" },
  { name: "eSearch", zhName: "电子搜索" },
  { name: "GoGoGo", zhName: "前进工具" },
  { name: "NotifyMe", zhName: "通知我" },
  { name: "Immich", zhName: "照片管理" },
  { name: "TempEmail", zhName: "临时邮箱" },
  { name: "ProxyCat", zhName: "代理猫" },
  { name: "PicX", zhName: "图片管理" },
  { name: "AcademicHomepage", zhName: "学术主页" },
  { name: "SpotifyPlayer", zhName: "音乐播放器" },
  { name: "ShotEasy", zhName: "轻松截图" },
  { name: "ImageToolbox", zhName: "图像工具箱" },
  { name: "Docmost", zhName: "文档中心" },
  { name: "WatermarkTool", zhName: "水印工具" },
  { name: "ProxyPin", zhName: "代理收藏" },
  { name: "QuickWaitlist", zhName: "快速候补" },
  { name: "TelegramDownloader", zhName: "电报下载器" },
  { name: "SocialUpload", zhName: "社交上传" },
  { name: "Cobalt", zhName: "钴工具" },
  { name: "HiddenBar", zhName: "隐藏栏" },
  { name: "CaesiumCompressor", zhName: "铯压缩器" },
  { name: "ITTools", zhName: "IT工具集" },
  { name: "ResDownloader", zhName: "资源下载器" },
  { name: "StreamRec", zhName: "流媒体录制" },
  { name: "DepthOfField", zhName: "景深处理" },
  { name: "DouyinVue", zhName: "抖音浏览" },
  { name: "QuickRecorder", zhName: "快速录制" },
  { name: "HanziWriter", zhName: "汉字书写" },
  { name: "PingvinShare", zhName: "企鹅共享" },
  { name: "Pake", zhName: "打包工具" },
  { name: "Certimate", zhName: "证书伴侣" },
  { name: "SimpleMindMap", zhName: "简易思维导图" },
  { name: "Plate", zhName: "编辑器" },
  { name: "FScan", zhName: "快速扫描" },
  { name: "SimpleLive", zhName: "简易直播" },
  { name: "XiaoMusic", zhName: "小音乐" },
  { name: "DeeplxFile", zhName: "文件翻译" },
  { name: "IPTVnator", zhName: "网络电视" },
  { name: "EcoPaste", zhName: "生态粘贴" },
  { name: "RenderCV", zhName: "简历生成" },
  { name: "VutronMusic", zhName: "音乐播放器" },
  { name: "Squish", zhName: "压缩工具" },
  { name: "PairDrop", zhName: "配对传输" },
  { name: "Checkmate", zhName: "检查助手" },
  { name: "MyIP", zhName: "我的IP" },
  { name: "Presenterm", zhName: "终端演示" },
  { name: "FileConverter", zhName: "文件转换器" },
  { name: "CodeSnap", zhName: "代码截图" },
  { name: "IPHelper", zhName: "IP助手" },
  { name: "FastSend", zhName: "快速发送" },
  { name: "AcademicProject", zhName: "学术项目" },
  { name: "SiteOneCrawler", zhName: "站点爬虫" },
  { name: "WechatBackup", zhName: "微信备份" },
  { name: "Neko", zhName: "猫咪浏览器" },
  { name: "KoodoReader", zhName: "库读阅读器" },
  { name: "WindTerm", zhName: "风终端" },
  { name: "MarkText", zhName: "标记文本" },
  { name: "RightMenuMaster", zhName: "右键菜单大师" },
  { name: "FileCentipede", zhName: "文件蜈蚣" },
  { name: "PaperlessNGX", zhName: "无纸化系统" },
  { name: "WordsFunny", zhName: "趣味单词" },
  { name: "AcademicTemplate", zhName: "学术模板" },
  { name: "OnurDev", zhName: "开发助手" },
  { name: "PinyinPro", zhName: "拼音专业版" },
  { name: "VmailDEV", zhName: "虚拟邮件开发" },
  { name: "Lux", zhName: "光线工具" },
  { name: "Applite", zhName: "轻量应用" },
  { name: "PearRec", zhName: "梨子录制" },
  { name: "Huntly", zhName: "猎取工具" },
  { name: "LapisCV", zhName: "青金石简历" },
  { name: "HitomiDownloader", zhName: "瞳下载器" },
  { name: "WeWeRSS", zhName: "微微RSS" },
  { name: "GitButler", zhName: "Git管家" },
  { name: "WebCheck", zhName: "网站检查" },
];

// 项目类型
export const projectTypes = ["primary", "secondary", "default"];

// 项目标签
export const projectTags = {
  web: "网页应用",
  desktop: "桌面应用",
  mobile: "移动应用",
  backend: "后端服务",
  tool: "工具类",
  content: "内容类",
};

// 获取随机项目名称列表
export const getRandomProjectNames = (count = 15) => {
  // 复制数组，避免修改原数组
  const shuffled = [...projectNamesList].sort(() => Math.random() - 0.5);
  // 返回指定数量的元素
  return shuffled.slice(0, count);
};
